### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by liuts933** [liushilive/htmlreport#1]
Traceback (most recent call last):
  File "/Users/liutiesong/PycharmProjects/ui_autotest/run_cases.py", line 7, in <module>
    import unittest,  os, HTMLReport
  File "/Library/Python/3.8/site-packages/HTMLReport/__init__.py", line 26, in <module>
    from .src.test_runner import TestRunner
  File "/Library/Python/3.8/site-packages/HTMLReport/src/test_runner.py", line 47, in <module>
    class TestRunner(TemplateMixin, TestSuite):
  File "/Library/Python/3.8/site-packages/HTMLReport/src/test_runner.py", line 368, in TestRunner
    def _generate_report_test(self, rows, tc_xml, cid, tid, n: ResultStatus, t, o, i, r, s: dict[int, ResultStatus], d):
TypeError: 'type' object is not subscriptable

python version = 3.8.2

**Comment by liuts933** [comment]
<img width="1890" alt="image" src="https://user-images.githubusercontent.com/8381627/185394969-ae794c01-5e91-4077-ad83-6d9e3f30e665.png">

**Comment by miangangzhen** [comment]
I have meet the same issue

**Comment by Euraxluo** [comment]
dict[str, Any] i have error too
